version: '3.0'
services:
  auth:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.6
    environment:
      - 'JSON_CONFIG={"interactiveLogin": false}'
    ports:
      - '8080:8080'
    hostname: auth 
  rapi:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - auth
    environment:
      - 'AUTHSERVER=http://auth:8080/default/.well-known/openid-configuration'
      - 'ROCKET_PORT=3000'
      - 'ROCKET_ADDRESS=0.0.0.0'
